/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { CreateCall, CreateCallInterface } from "../CreateCall";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "newContract",
        type: "address",
      },
    ],
    name: "ContractCreation",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "deploymentData",
        type: "bytes",
      },
    ],
    name: "performCreate",
    outputs: [
      {
        internalType: "address",
        name: "newContract",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "deploymentData",
        type: "bytes",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
    ],
    name: "performCreate2",
    outputs: [
      {
        internalType: "address",
        name: "newContract",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610334806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80634847be6f1461003b5780634c8c9ea11461006a575b600080fd5b61004e610049366004610267565b61007d565b6040516001600160a01b03909116815260200160405180910390f35b61004e6100783660046102b7565b610124565b60008183518460200186f590506001600160a01b0381166100e15760405162461bcd60e51b815260206004820152601960248201527810dbdd5b19081b9bdd0819195c1b1bde4818dbdb9d1c9858dd603a1b60448201526064015b60405180910390fd5b6040516001600160a01b03821681527f4db17dd5e4732fb6da34a148104a592783ca119a1e7bb8829eba6cbadef0b5119060200160405180910390a19392505050565b600081516020830184f090506001600160a01b0381166101825760405162461bcd60e51b815260206004820152601960248201527810dbdd5b19081b9bdd0819195c1b1bde4818dbdb9d1c9858dd603a1b60448201526064016100d8565b6040516001600160a01b03821681527f4db17dd5e4732fb6da34a148104a592783ca119a1e7bb8829eba6cbadef0b5119060200160405180910390a192915050565b634e487b7160e01b600052604160045260246000fd5b600082601f8301126101eb57600080fd5b813567ffffffffffffffff80821115610206576102066101c4565b604051601f8301601f19908116603f0116810190828211818310171561022e5761022e6101c4565b8160405283815286602085880101111561024757600080fd5b836020870160208301376000602085830101528094505050505092915050565b60008060006060848603121561027c57600080fd5b83359250602084013567ffffffffffffffff81111561029a57600080fd5b6102a6868287016101da565b925050604084013590509250925092565b600080604083850312156102ca57600080fd5b82359150602083013567ffffffffffffffff8111156102e857600080fd5b6102f4858286016101da565b915050925092905056fea26469706673582212205971c22241ce6aa8f75efd37915c7ce3ddc3fe65eb770d92c8250f7b314ee9f464736f6c634300080f0033";

type CreateCallConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CreateCallConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CreateCall__factory extends ContractFactory {
  constructor(...args: CreateCallConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<CreateCall> {
    return super.deploy(overrides || {}) as Promise<CreateCall>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): CreateCall {
    return super.attach(address) as CreateCall;
  }
  override connect(signer: Signer): CreateCall__factory {
    return super.connect(signer) as CreateCall__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CreateCallInterface {
    return new utils.Interface(_abi) as CreateCallInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): CreateCall {
    return new Contract(address, _abi, signerOrProvider) as CreateCall;
  }
}
