import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'


const Home: NextPage = () => {
  return (
    // <div className={styles.container}>
    <>
      <Head>
        <title>Zebra</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Welcome to Zebra (HOME FILL)</h1>
      </div>


    </>

  )
}

export default Home
