/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  DeployBase,
  DeployBaseInterface,
} from "../../DeployBase.s.sol/DeployBase";

const _abi = [
  {
    inputs: [],
    name: "IS_SCRIPT",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "vm",
    outputs: [
      {
        internalType: "contract Vm",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60806040526000805460ff1916600117905534801561001d57600080fd5b5060bf8061002c6000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80633a768463146037578063f8ccbf4714606e575b600080fd5b6051737109709ecfa91a80626ff3989d68f67f5b1dd12d81565b6040516001600160a01b0390911681526020015b60405180910390f35b600054607a9060ff1681565b6040519015158152602001606556fea26469706673582212202f0d0dcf7edc87e9462a9c3f09008442928118253d9d9eb57e5cfc0d3a1a914564736f6c634300080f0033";

type DeployBaseConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DeployBaseConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DeployBase__factory extends ContractFactory {
  constructor(...args: DeployBaseConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<DeployBase> {
    return super.deploy(overrides || {}) as Promise<DeployBase>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DeployBase {
    return super.attach(address) as DeployBase;
  }
  override connect(signer: Signer): DeployBase__factory {
    return super.connect(signer) as DeployBase__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DeployBaseInterface {
    return new utils.Interface(_abi) as DeployBaseInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DeployBase {
    return new Contract(address, _abi, signerOrProvider) as DeployBase;
  }
}
