# Generated by Django 3.2.13 on 2022-07-10 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserWalletInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_wallet_address', models.CharField(max_length=42)),
                ('gnosis_safe_address', models.CharField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='ZebraNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierAddress', models.CharField(max_length=42)),
                ('nftAddress', models.CharField(max_length=42)),
                ('nftImage', models.CharField(max_length=200)),
                ('tokenId', models.IntegerField()),
                ('pricePerSecond', models.IntegerField()),
                ('maxRentDuration', models.IntegerField()),
                ('nonce', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('renterWalletInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renter_wallet_info', to='zebra.userwalletinfo')),
                ('supplierWalletInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_wallet_info', to='zebra.userwalletinfo')),
            ],
        ),
    ]
