# Generated by Django 3.2.13 on 2022-07-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offers',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
