# Generated by Django 3.2.13 on 2022-07-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zebranft',
            name='renterWalletInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renter_wallet_info', to='zebra.userwalletinfo'),
        ),
        migrations.AlterField(
            model_name='zebranft',
            name='supplierWalletInfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_wallet_info', to='zebra.userwalletinfo'),
        ),
    ]
