# Generated by Django 3.2.13 on 2022-07-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0002_auto_20220708_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zebranft',
            name='colletion',
        ),
        migrations.AddField(
            model_name='zebranft',
            name='supplierAddress',
            field=models.CharField(default='filler_address', max_length=42),
            preserve_default=False,
        ),
    ]
