# Generated by Django 3.2.13 on 2022-07-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zebra', '0002_auto_20220710_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zebranft',
            name='renterAddress',
        ),
    ]
