/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../common";
import type {
  DeployAZebraSafeRinkeby,
  DeployAZebraSafeRinkebyInterface,
} from "../../DeployAZebraSafeRinkeby.s.sol/DeployAZebraSafeRinkeby";

const _abi = [
  {
    inputs: [],
    name: "IS_SCRIPT",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "run",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "vm",
    outputs: [
      {
        internalType: "contract Vm",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60806040526000805460ff1916600117905534801561001d57600080fd5b506103608061002d6000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80633a76846314610046578063c04062261461007e578063f8ccbf4714610088575b600080fd5b610061737109709ecfa91a80626ff3989d68f67f5b1dd12d81565b6040516001600160a01b0390911681526020015b60405180910390f35b6100866100a5565b005b6000546100959060ff1681565b6040519015158152602001610075565b60408051637fb5297f60e01b8152905173e11470a714bc2061335cc15ebc453b0f95cef1b591737109709ecfa91a80626ff3989d68f67f5b1dd12d91637fb5297f9160048082019260009290919082900301818387803b15801561010857600080fd5b505af115801561011c573d6000803e3d6000fd5b505050506000816001600160a01b031663d92dc46c6040518163ffffffff1660e01b81526004016020604051808303816000875af1158015610162573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906101869190610295565b90507f885cb69240a935d632d79c317109709ecfa91a80626ff3989d68f67f5b1dd12d60001c60601b60601c6001600160a01b03166376eadd366040518163ffffffff1660e01b8152600401600060405180830381600087803b1580156101ec57600080fd5b505af1158015610200573d6000803e3d6000fd5b50505050610230816040518060400160405280600a8152602001697a65627261207a61666560b01b815250610234565b5050565b610230828260405160240161024a9291906102c5565b60408051601f198184030181529190526020810180516001600160e01b031663759f86bb60e01b17905280516a636f6e736f6c652e6c6f67602083016000808483855afa5050505050565b6000602082840312156102a757600080fd5b81516001600160a01b03811681146102be57600080fd5b9392505050565b60018060a01b038316815260006020604081840152835180604085015260005b81811015610301578581018301518582016060015282016102e5565b81811115610313576000606083870101525b50601f01601f19169290920160600194935050505056fea26469706673582212200c63db102916af72f2d1279e8e5782d22d543b9113592e2375762478d0086cee64736f6c634300080f0033";

type DeployAZebraSafeRinkebyConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DeployAZebraSafeRinkebyConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DeployAZebraSafeRinkeby__factory extends ContractFactory {
  constructor(...args: DeployAZebraSafeRinkebyConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<DeployAZebraSafeRinkeby> {
    return super.deploy(overrides || {}) as Promise<DeployAZebraSafeRinkeby>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DeployAZebraSafeRinkeby {
    return super.attach(address) as DeployAZebraSafeRinkeby;
  }
  override connect(signer: Signer): DeployAZebraSafeRinkeby__factory {
    return super.connect(signer) as DeployAZebraSafeRinkeby__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DeployAZebraSafeRinkebyInterface {
    return new utils.Interface(_abi) as DeployAZebraSafeRinkebyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DeployAZebraSafeRinkeby {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as DeployAZebraSafeRinkeby;
  }
}
